# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3070c87e076b1ab4fc88cd1f065534bfff86ba87f489f95eea6a67f9bd6267469f9b20ff5bb4d1705db00b6eee92821aa3226ea242a81d6c744e6fc73cc556e7

test:
  secret_key_base: eb4aae868300b20d1ae9ff1a1abfccd0ec065e9a4ac9397f54099747cafd5b548f8124500abf465799e957101c6fa1539591efd9656892992b767f04b31b6081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
